# Generated by Django 5.2.1 on 2025-11-21 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_address', models.TextField(max_length=300)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('emp_department', models.CharField(choices=[('Manager', 'Manager'), ('Frontend_Developer', 'Frontend_Developer'), ('Backend_Developer', 'Backend_Developer'), ('Fullstack_Developer', 'Fullstack_Developer'), ('Designer', 'Designer'), ('QA', 'QA')], max_length=20)),
                ('emp_position', models.CharField(choices=[('intern', 'intern'), ('junior', 'junior'), ('Associate', 'Associate'), ('senior', 'senior'), ('lead', 'lead'), ('manager', 'manager')])),
                ('emp_hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emp_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employee Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmpAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='empcrud.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField(blank=True, max_length=300, null=True)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leave', to='empcrud.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Annual Leave', 'Annual Leave'), ('Maternity Leave', 'Maternity Leave'), ('Paternity Leave', 'Paternity Leave'), ('Bereavement Leave', 'Bereavement Leave'), ('Unpaid Leave', 'Unpaid Leave')], max_length=20, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, max_length=30, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('remaining_days', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='empcrud.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=True, max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='empcrud.employeedetail')),
                ('request_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empcrud.leaverequest')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=25)),
                ('project_description', models.TextField(blank=True, max_length=300, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('On_Hold', 'On_Hold'), ('Completed', 'Completed')])),
                ('project_deadline', models.DateField()),
                ('project_document', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empcrud.employeedetail')),
                ('project_member', models.ManyToManyField(blank=True, related_name='Project_Member', to='empcrud.employeedetail')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=150, verbose_name='Task Name')),
                ('task_description', models.TextField(blank=True, max_length=300, verbose_name='Task Description')),
                ('Status', models.CharField(blank=True, choices=[('To_Do', 'To_Do'), ('In_Progress', 'In_Progress'), ('Completed', 'Completed')], default='To_Do', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='empcrud.employeedetail', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='empcrud.employeedetail', verbose_name='Created By')),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='empcrud.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date'],
            },
        ),
    ]
