# Generated by Django 5.2.1 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproved',
            name='reason',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='LeaveRejected',
        ),
    ]
