# Generated by Django 5.2.1 on 2025-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0002_leaveapproved_reason_delete_leaverejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproved',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
