# Generated by Django 5.2.1 on 2025-11-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empcrud', '0003_alter_leaveapproved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapproved',
            name='request_leave',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empcrud.leaverequest'),
        ),
    ]
